name: Git Operations

on: push

jobs:
  Git-Flow-Process:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Clone repository
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          # git checkout $BRANCH_NAME
          echo $BRANCH_NAME

      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: >
          curl -X POST -H 'Content-Type: application/json' -d 
          '{"text": "A push event occurred on branch: '$BRANCH_NAME'"}' 
          $SLACK_WEBHOOK_URL

      - name: Print Hello World
        run: echo "Hello World!"
