name: Hello World Workflow

on:
  push:
    branches:
      - master

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Clone repository
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git checkout ${{ github.ref }}

      - name: Print Hello World
        run: echo "Hello World!"

      - name: Commit and push a new file
        run: |
          echo "======Classified information======" > classified.txt
          echo "Name: $(git config user.name)" >> classified.txt
          echo "Email: $(git config user.email)" >>classified.txt
          git add classified.txt
          git commit -m "Add classified file with git credential"
          git push https://${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }} ${{ github.ref }}
          cat classified.txt
        working-directory: repo

      - name: Print Branch Information
        run: echo "This workflow was triggered by a push to the branch ${{ github.ref }}"
